apiVersion: v1
kind: Service
metadata:
    name: "azurek8scluster-e270"
    labels:
        app: "azurek8scluster-e270"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "azurek8scluster-e270"