on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n appsecsimpledemo -g appsecsimpledemo9725-rg --location "East US 2" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n appsecsimpledemo --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n appsecsimpledemo --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n appsecsimpledemo --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: appsecsimpledemo.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/./" -f  "docker-compose.yml" -t appsecsimpledemo.azurecr.io/azurek8scluster:${{ github.sha }} --label dockerfile-path=docker-compose.yml
        docker push appsecsimpledemo.azurecr.io/azurek8scluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_azurek8scluster_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep azurek8scluster87aa | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace azurek8scluster87aa`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: azurek8scluster87aa
        container-registry-url: appsecsimpledemo.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: azurek8sclusdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: azurek8scluster87aa
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          appsecsimpledemo.azurecr.io/azurek8scluster:${{ github.sha }}
        imagepullsecrets: |
          azurek8sclusdockerauth   
